services:
  debug_nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:80"
      - "9966:9966"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG_SOURCES_DIR=./rootfs/etc/nginx
    develop:
      watch:
        - action: sync+restart
          path: ./rootfs/etc/nginx/lua
          target: /etc/nginx/lua
#    volumes:
#      - ./rootfs/etc/nginx:/etc/nginx