services:
  debug_nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:80"
      - "9966:9966"
    environment:
      - DEBUG_SOURCES_DIR=./rootfs/etc/nginx
    develop:
      watch:
        - action: sync+restart
          path: ./rootfs/etc/nginx
          target: /etc/nginx